name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.3.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.5
  fl_chart: ^0.70.2
  firebase_storage: ^12.4.4
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^19.0.0
  http: ^1.3.0
  flutter_gemini: ^3.0.0
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.1
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/images/nutriselect.png"
  adaptive_icon_background: "#ffffff"


flutter:
  uses-material-design: true

  assets:
    - assets/images/nutriselect.png
    - assets/images/visa.png
    - assets/images/master.jpg