// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYpiLnJc4fNWYL5bd71k3BXRVO3pvcwD4',
    appId: '1:298312006505:web:bcceb15525651d94f85bf8',
    messagingSenderId: '298312006505',
    projectId: 'instagram-clone-b1843',
    authDomain: 'instagram-clone-b1843.firebaseapp.com',
    storageBucket: 'instagram-clone-b1843.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDy2Wx_LPoL46Dg0tWPtXxA_yFtdOQOAU',
    appId: '1:298312006505:android:2233d63adb6ec5dcf85bf8',
    messagingSenderId: '298312006505',
    projectId: 'instagram-clone-b1843',
    storageBucket: 'instagram-clone-b1843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-f9f9lG7z0vqOti15bKed39y6jeoIGQ',
    appId: '1:298312006505:ios:d0de4e3aebe1f338f85bf8',
    messagingSenderId: '298312006505',
    projectId: 'instagram-clone-b1843',
    storageBucket: 'instagram-clone-b1843.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs-f9f9lG7z0vqOti15bKed39y6jeoIGQ',
    appId: '1:298312006505:ios:d0de4e3aebe1f338f85bf8',
    messagingSenderId: '298312006505',
    projectId: 'instagram-clone-b1843',
    storageBucket: 'instagram-clone-b1843.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYpiLnJc4fNWYL5bd71k3BXRVO3pvcwD4',
    appId: '1:298312006505:web:cd50adfa2894f606f85bf8',
    messagingSenderId: '298312006505',
    projectId: 'instagram-clone-b1843',
    authDomain: 'instagram-clone-b1843.firebaseapp.com',
    storageBucket: 'instagram-clone-b1843.appspot.com',
  );

}